### ISSUE TITLE
Declaration of overriden validate() method is incorrect in version 2.0.2

### ISSUE THREAD

**Issue by VladimirBerdnik** [Saritasa/php-laravel-controllers#4]
Got `Declaration of **Saritasa\Laravel\Controllers\Api\BaseApiController::validate(Dingo\Api\Http\Request $request, array $rules, array $messages = Array, array $customAttributes = Array)** should be compatible with **Saritasa\Laravel\Controllers\BaseController::validate(Illuminate\Http\Request $request, array $rules, array $messages = Array, array $customAttributes = Array)**` after start laravel application.

Sorry, don't have time today to create PR

**Comment by populov** [comment]
Fixed in [2.0.4](https://github.com/Saritasa/php-laravel-controllers/releases/tag/2.0.4)
