### ISSUE TITLE
Improvement of ApiResourceRegistrar

### ISSUE THREAD

**Issue by VladimirBerdnik** [Saritasa/php-laravel-controllers#5]
Now ApiResourceRegistrar has hardcoded routes for common GET, PUT, DELETE resources like `categories/{id}`. I suggest to have option to pass into ApiResourceRegistrar and have ability to change this hardcoded **{id}** parameter. 
It is need to have ability to bind models automatically with DI: https://laravel.com/docs/5.4/routing#route-model-binding

Now it is also works, but variable name should be the same as in route:
```php
// GET /categories/{id}
public function show(Category $id)
```
my suggestion is to have ability change this hardcoded identifier and make variable name more appropriate:
```php
// GET /categories/{category}
public function show(Category $category)
```

**Comment by populov** [comment]
Ok, do it! :)

**Comment by VladimirBerdnik** [comment]
Yes, of cource, i'll do it when i'll have time. But maybe someone wants to contribute and i posted this issue to point to possible feature
